### PR TITLE
Add Python 3 compatibility

### PR DESCRIPTION
**Pull request by mindsolve**
This PR adds Python 3 compatibility in addition to 2.7 to this project.

### CODE REVIEW

**Comment by inbilla** [comment]
That all looks fine to me, I don't have it running locally to test, but the changes look fine.
Happy to merge if you're ready?
Thanks for the contribution

**Comment by mindsolve** [comment]
I made those changes some time ago, and at that time tested the server locally - though only quite shallowly.
I then saw that somebody else recently used my Python3-compat branch, so I thought I should contribute it back to the main project. From my point of view, this PR should be ready to be merged.

**Comment by inbilla** [comment]
Thanks again,
In future I have a mind to re-attempt to put this service into a linux docker container, and add some minimal automated testing.

**Comment by mindsolve** [comment]
Very nice. Thank **you** for this project and the fast merge!

Porting this project to Linux would be very nice and (as fas as I can tell) make it the only symbol file proxy with Linux support.
If you need somebody with absolutely no experience in Windows APIs or Symbol files - I would be glad to help with that :D

**Pull request merged**
